// Copyright ProjectBH. All Rights Reserved.
#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "BHCameraOcclusionComponent.generated.h"

class UMeshComponent;
class UMaterialInterface;
class UMaterialInstanceDynamic;
class APlayerController;
class USpringArmComponent;
class UCameraComponent;
class USkeletalMeshComponent;

USTRUCT()
struct FBHCameraOccluderState
{
	GENERATED_BODY()
	UPROPERTY() TWeakObjectPtr<UMeshComponent> Mesh;
	UPROPERTY() TArray<TObjectPtr<UMaterialInterface>> Originals;
	UPROPERTY() TArray<TObjectPtr<UMaterialInstanceDynamic>> Overrides;
	float LastSeenTime = 0.0f;
	float Amount = 0.0f;
	bool bHiddenByThisComponent = false;
};

/** Local view presentation only. Never changes gameplay collision or navigation. */
UCLASS(ClassGroup = (Camera), meta = (BlueprintSpawnableComponent))
class PROJECTBH_API UBHCameraOcclusionComponent : public UActorComponent
{
	GENERATED_BODY()
public:
	UBHCameraOcclusionComponent();
	virtual void TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction) override;
	virtual void EndPlay(const EEndPlayReason::Type EndPlayReason) override;
	virtual void Deactivate() override;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Camera Occlusion")
	bool bEnabled = true;
	/** Actor or component tag. Tag walls/roofs, never a combined floor-and-wall mesh. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Camera Occlusion")
	FName OccluderTag = TEXT("CameraOccluder");
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Camera Occlusion", meta = (ClampMin = "0.02", Units = "s"))
	float ProbeInterval = 0.1f;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Camera Occlusion", meta = (ClampMin = "1", Units = "cm"))
	float ProbeRadius = 45.0f;
	/** Radius at the player's plane. The material projects this around the player in the view. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Camera Occlusion", meta = (ClampMin = "1", Units = "cm"))
	float CutoutRadius = 180.0f;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Camera Occlusion", meta = (ClampMin = "0.01", Units = "s"))
	float FadeDuration = 0.2f;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Camera Occlusion", meta = (ClampMin = "0", Units = "s"))
	float RestoreDelay = 0.25f;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Camera Occlusion")
	FVector FocusOffset = FVector(0, 0, 25);
	/** Holds the intended camera distance while this component owns the local view. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Camera Occlusion")
	bool bKeepCameraDistance = true;
	/** Unprepared tagged meshes are hidden in this player's view until materials are set up. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Camera Occlusion")
	bool bHideUnpreparedOccluders = true;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Camera Occlusion|Silhouette")
	bool bEnablePlayerSilhouette = true;
	/** Generated by Scripts/Editor/setup_camera_occlusion.py. Requires Custom Depth with Stencil. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Camera Occlusion|Silhouette")
	TSoftObjectPtr<UMaterialInterface> SilhouetteMaterial;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Camera Occlusion|Silhouette", meta = (ClampMin = "1", ClampMax = "255"))
	int32 SilhouetteStencil = 253;

private:
	void BeginLocalView(APlayerController* Controller);
	void RestoreLocalView();
	void Probe(const FVector& CameraLocation, const FVector& Focus);
	void TrackMesh(UMeshComponent* Mesh);
	void RestoreMesh(FBHCameraOccluderState& State);
	UPROPERTY(Transient) TArray<FBHCameraOccluderState> Occluders;
	UPROPERTY(Transient) TWeakObjectPtr<APlayerController> LocalController;
	UPROPERTY(Transient) TWeakObjectPtr<USpringArmComponent> SpringArm;
	UPROPERTY(Transient) TWeakObjectPtr<UCameraComponent> Camera;
	UPROPERTY(Transient) TWeakObjectPtr<USkeletalMeshComponent> SilhouetteMesh;
	UPROPERTY(Transient) TObjectPtr<UMaterialInstanceDynamic> SilhouetteInstance;
	float ProbeElapsed = 0.0f;
	bool bSavedCollisionTest = false;
	bool bOwnsSpringArm = false;
	bool bUsePerViewHiding = false;
	bool bSavedCustomDepth = false;
	int32 SavedStencil = 0;
	uint8 SavedStencilMask = 0;
};
